name: CustomShopUI
main: SaltyPixelDevz\CustomShopUIv2\Shop
version: 4.0.2
api: [3.0.0]
author: SaltyPixelDevz
website: http://saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens CustomShopUI"
permissions:
  shop.shop:
    default: true
    description: "Allows use of the /shop command"